### ISSUE TITLE
Deal with Authentication error on Demo pages

### ISSUE THREAD

**Issue by BigAB** [donejs/bitcentive#112]
Demo pages currently show this error in the console:

![image](https://cloud.githubusercontent.com/assets/76821/20358549/d14af8a6-abf1-11e6-8682-e2117850596e.png)

Let's figure out what is causing it and make sure it doesn't throw on demo pages

**Comment by marshallswain** [comment]
This error is caused by the current version of the `feathers-authentication` plugin.  It has a bad API that requires a call to `app.authenticate()` before it can determine if the user is logged in with a valid token.  This won't be necessary once the new `feathers-authentication-client` is released, which will be a few more weeks.  With the current API, if you call `app.authenticate()` with no params, it will look for a token in storage and send the token, even if it's expired.  We might be able to prevent this error by checking the validity of the token before we make the call to `authenticate` in the `can-connect-feathers/session` behavior.

**Comment by marshallswain** [comment]
Looking into this more, this is actually caused by can-zone here: https://github.com/canjs/can-zone/blob/master/lib/tasks.js#L109.  Even though I'm catching the rejected promise, can-zone is rethrowing it whether it's an actual error object or a string.  @matthew might know more, but the only way I know of to get around this is right now is to not make the request at all.  I can make a utility for can-connect-feathers to handle this.  Usage would look like this:

```js
import {hasValidToken} from 'can-connect-feathers/utils';

const AppViewModel = DefineMap.extend({
  session: {
    value () {
      // Authenticate the socket if we have a stored, valid token
      if(hasValidToken('feathers-jwt')){
        new Session().save();
      }
    }
});
```
