### ISSUE TITLE
Data changes don't realtime sync with other clients.

### ISSUE THREAD

**Issue by marshallswain** [donejs/bitcentive#193]
The socket messages are being received on the second window, but the data doesn't automatically update for the unchecked sections:

- [ ] Open Source Projects
- [ ] Client Projects
- [x] Contributions
- [x] Contributors

**Comment by ilyavf** [comment]
@justinbmeyer What u suggested to start with:
```js
ContributionMonth = DefineMap.extend({
    removeAttr: true
},{
    monthlyClientProjects: {set: function(props){
        return smartMerge(this.monthlyClientProjects, props)
    }}
})
```

does not work because of the following:

`removeAttr: true` adds to ContributionMonth, and in `can-connect/can/map/map` it looks for behaviour’s `removeAttr` in https://github.com/canjs/can-connect/blob/master/can/map/map.js#L328 :
```js
        behavior[funcName+"Instance"] = function (instance, props) {
            var constructor = instance.constructor;

            // Update attributes if attributes have been passed
            if(props && typeof props === 'object') {
                if("set" in instance) {
                    instance.set(isFunction(props.get) ? props.get() : props, this.constructor.removeAttr || false);
                }
             ...
```

so `this.constructor.removeAttr` does not refer to `instance.constructor.removeAttr`.

**Comment by ilyavf** [comment]
@justinbmeyer Also, to use `smartMerge` in a setter we still need to make `.attr()` go through the setter. It might be related to https://github.com/canjs/can-define/issues/96

**Comment by ilyavf** [comment]
@justinbmeyer I m looking at how to use can-connect for this as u also suggested, smth like:
```js
connect( [
    updateMap: smartMerge
] )
```
