### ISSUE TITLE
Refresh a non-home page navigates to home

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#277]
When I refresh `http://localhost:3030/development.html#!contributors` i m getting to dashboard.

This has something to do with page getter depending on session:
```js
  page: {
    serialize: true,
    get (page) {
      if (this.session) {    // <<<<<<  this is false initially; session is set asynchronously (?)
        if (page === 'home') {
          page = 'dashboard';
        }
      } else {
        if (pages[page] === 'private') {
          page = 'home';
        }
      }
```

Do we need to consider some `isAuthenticating` state of the Session?

`can-connect-feathers` had a change with `isAuthenticated` that we reverted by mistake (the bug was due to can-connect).

**Comment by justinbmeyer** [comment]
one solution might be to delay `route.ready()` until the session is figured out.  @matthewp would this be hard for done-autorender?

Another solution is to use something other than `page` for the actual page the user should be on.

For example, it could be `displayedPage`.  The `displayedPage` would be `login` if the user wasn't logged in.  Otherwise, it would match `page`.

**Comment by matthewp** [comment]
I think some type of isAuthenticated state is the most powerful of the options personally.

**Comment by justinbmeyer** [comment]
```
page: "string",
get displayedPage(){ 
  if(Session.current === undefined ) {
    return "spinner"
  }
  else if ( Session.current === null ) {
    return "login"
  }
  else {
    return this.page;
  }
}
```

**Comment by ilyavf** [comment]
Fixed. Verified on prod.
